### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by na-am** [SomethingWithComputers/pixoo#26]
I just tried to install it w/o success:

```
pi@raspberrypi:~ $ python3 -V
Python 3.9.2
pi@raspberrypi:~ $ pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
pi@raspberrypi:~ $ pip install pixoo
ERROR: Could not find a version that satisfies the requirement pixoo
ERROR: No matching distribution found for pixoo
```

**Comment by jwpyle3** [comment]
Looks like you need python 3.10 or higher according to the setup.py file.  python_requires='>=3.10'

**Comment by na-am** [comment]
thx for the quick answer
You are right, trying to install with cloned package says exactly python must be >= 3.10
```
.........
ERROR: Package 'pixoo' requires a different Python: 3.9.2 not in '>=3.10'`
```

no success after manually upgrade to 3.10.2

```
pi@raspberrypi:/tmp $ python3 -V
Python 3.10.2
pi@raspberrypi:/tmp $ pip install pixoo
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.VersionConflict: (pip 21.2.4 (/usr/local/lib/python3.10/site-packages), Requirement.parse('pip==20.3.4'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'pip==20.3.4' distribution was not found and is required by the application
```

**Comment by SomethingWithComputers** [comment]
The reason seems to be in the message you posted:

`pip._vendor.pkg_resources.VersionConflict: (pip 21.2.4 (/usr/local/lib/python3.10/site-packages), Requirement.parse('pip==20.3.4'))`

So try updating pip as well and see if that fixes it!

**Comment by SomethingWithComputers** [comment]
@na-am hey there! If updating `pip` fixed it, then I can close this issue :). I'll give it a few more days if you need some more help, but otherwise I'mma close this issue! (But you can of course open a new one if you have more questions at that point)
