### ISSUE TITLE
Unable to find tiny.png on running examples.py

### ISSUE THREAD

**Issue by bigboss97** [SomethingWithComputers/pixoo#27]
Where can I find the file _tiny.png_. I'm getting following errors:
```
E:\work\Android\Pixoo64\pixoo-main>python examples.py
[.] Counter loaded and stored: 1
Traceback (most recent call last):
  File "E:\work\Android\Pixoo64\pixoo-main\examples.py", line 68, in <module>
    pixoo.draw_image('tiny.png')  # Adds image at path 'tiny.png' at default location (0, 0)
  File "E:\work\Android\Pixoo64\pixoo-main\src\pixoo\objects\pixoo.py", line 101, in draw_image
    Image.Image) else Image.open(
  File "C:\Users\home\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\work\\Android\\Pixoo64\\pixoo-main\\tiny.png'
```

**Comment by SomethingWithComputers** [comment]
It's an example name for an image. You can use any other image, like this one: https://dummyimage.com/64 and store it as "tiny.png". Or, use any other PNG-image you have laying around. Just place it in the same directory as where the script is running from and adjust the name accordingly :).

**Comment by BitwiseAndrea** [comment]
I thought that the logic in pixoo.py implied it lazily created tiny.png, if it wasn't already there
